apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
data:
  rabbitmq.conf: |
    loopback_users = none
    consumer_timeout = 14400000
    max_message_size = 536870912