apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  type: {{ .Values.service.type }}
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.port.amqp }}
      targetPort: {{ .Values.port.amqp }}
    - name: management
      port: {{ .Values.port.management }}
      targetPort: {{ .Values.port.management }}